### ISSUE TITLE
Yuliana's contact form reviews

### ISSUE THREAD

**Issue by Asiimwe-Mark** [Yulianav09/Portfolio#4]
1. Missing an expansion interaction in the bottom right corner of the message field
2. It has a big gap between the textarea field and the button.
3. The form was generally well implemented following the figma design.

**Comment by Yulianav09** [comment]
Thanks for the kind suggestions, the changes were implemented as requested

**Comment by Asiimwe-Mark** [comment]
You're welcome, happy coding 🎊
